pip install -r requirements.txt 2>nul || echo Requirements installation failed, continuing...
pip install ta-lib 2>nul || echo TA-Lib installation failed https://ta-lib.org/install, continuing...
streamlit run app.py
PAUSE